
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import { cn } from '@/lib/utils'
import StickyFooter from '@/components/StickyFooter'
import Providers from '@/components/Providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=' w-full h-[100vh]'>
      <body className={cn(inter.className) }>
        <Providers>
        <Header/>
       <main className='my-[5rem] overflow-y-auto  sticky md:static top[5rem] md:h-full h-200vh '>
 {children}
       </main>
       
        
       <StickyFooter/>
       </Providers>
        </body>
    </html>
  )
}
