
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import { cn } from '@/lib/utils'
import StickyFooter from '@/components/StickyFooter'
import Providers from '@/components/Providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="" dir='' >
      <body className='font-serif'>
        <Providers>
        <Header />
       <main className=' my-[5rem]     sticky md:static top-[5rem] md:h-[100vh] h-[100vh] '>

  {children}
 
       </main>
       
        
       <StickyFooter/>
       </Providers>
        </body>
    </html>
  )
}
