import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";
import StickyFooter from "@/components/StickyFooter";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="" dir="">
      <body className="font-mono">
        <Providers>
          <Header />

          <main className=" mt-[5rem] sticky min-h-screen  top-[5rem] md:min-h-[100vh]  ">

            {children}
            <Footer />
            <Toaster />
          </main>

          <StickyFooter />
        </Providers>
      </body>
    </html>
  );
}
